require: rubocop-rails
# exclude spec folder flr all cops
AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
    
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Naming/FileName:
  Exclude:
    - config/_PUMA.rb
    - config/_SCHEDULE.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Style/SymbolArray:
  Exclude:
    - config/initializers/filter_parameter_logging.rb
Style/GlobalStdStream:
  Exclude:
    - config/environments/production.rb
Style/ClassAndModuleChildren:
  Exclude:
    - spec/spec_helper.rb
Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - Gemfile
Rails/Output:
  Exclude:
    - db/seeds.rb
    - app/jobs/example_job.rb
    - app/models/currency_rate.rb
    - config/environments/development.rb
    - config/initializers/_CHEWY.rb
    - config/initializers/_CONFIG.rb
    - config/initializers/_REDIS.rb
    - config/initializers/_SIDEKIQ.rb
Metrics/MethodLength:
  Exclude:
    - bin/helpers/docker.rb
    - app/controllers/demo_controller.rb
Style/OptionalBooleanParameter:
  Exclude:
    - bin/helpers/docker.rb
Style/OptionalBooleanParameter:
  Exclude:
    - bin/helpers/common.rb
Lint/UselessAssignment:
  Exclude:
    - bin/helpers/puma.rb
    - bin/helpers/sidekiq.rb
Style/GlobalVars:
  Exclude:
    - bin/helpers/common.rb
    - bin/helpers/helpers.rb
    - config/initializers/_REDIS.rb
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/development.rb
Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/rails_helper.rb
