services:
  react_frontend:
    image: node:14.17.6
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
    working_dir: /app
    environment:
      HOST: 0.0.0.0
      PORT: 3001
      
    command: sh -c "npm install && npm start"

  app:
    build: ./idempotent_total_amount
    ports:
      - "3000:3000"
    volumes:
      - ./idempotent_total_amount:/app
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: development
      IDEMPOTENT_KEY_TTL: 5
    command: sh -c "bundle install && bundle exec rails db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    networks:
    - backend
  db: 
    image: postgres:15.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    networks:
      - backend
  redis:
    image: redis:3.2.11
    networks:
      - backend

      
networks:
  backend: 
    driver: bridge